# ChurnSense AI - reproducible entry points.
# Every target runs through .venv so results do not depend on an activated shell.

# Interpreter used to CREATE the venv. Override when the default python3 is
# too old: `make setup PYTHON=python3.12`. The project needs >= 3.11 because
# pydantic 2.x calls typing.ForwardRef(is_class=...), added in 3.10.1, and
# shap >= 0.50 requires 3.11 — see docs/PROJECT_WALKTHROUGH.md.
PYTHON ?= python3
MIN_PYTHON := 3.11

PY := .venv/bin/python
PIP := $(PY) -m pip

.DEFAULT_GOAL := help
.PHONY: help setup check-python lock data eda train evaluate explain all test lint format audit app api clean

help:  ## Show the available targets
	@grep -hE '^[a-zA-Z_-]+:.*?## ' $(MAKEFILE_LIST) \
	 | awk 'BEGIN{FS=":.*?## "}{printf "  \033[36m%-12s\033[0m %s\n", $$1, $$2}'

setup: check-python  ## Create .venv and install the project with dev + notebook extras
	$(PYTHON) -m venv .venv
	$(PIP) install --upgrade pip setuptools wheel
	$(PIP) install -e ".[dev,notebook]"
	@echo "Done. Next: make data"

check-python:  ## Verify $(PYTHON) is new enough, before anything is created
	@$(PYTHON) -c 'import sys; raise SystemExit(0 if sys.version_info[:2] >= (3, 11) else 1)' \
	  2>/dev/null || { \
	    echo ""; \
	    echo "  '$(PYTHON)' is $$($(PYTHON) -V 2>&1 | cut -d" " -f2), but this project needs >= $(MIN_PYTHON)."; \
	    echo ""; \
	    echo "  Pick a newer interpreter:"; \
	    echo "      make setup PYTHON=python3.12"; \
	    echo ""; \
	    printf "  Found on PATH:"; \
	    for v in 3.11 3.12 3.13; do command -v python$$v >/dev/null && printf " python%s" $$v; done; \
	    echo ""; echo ""; \
	    exit 1; \
	  }

lock:  ## Freeze the resolved environment into requirements.txt
	@printf '# Generated by `make lock` - do not edit by hand.\n' > requirements.txt
	@printf '# Constraints live in pyproject.toml; this file is the resolved lock.\n' >> requirements.txt
	@printf '# Produced on Python %s\n' "$$($(PY) -c 'import platform;print(platform.python_version())')" >> requirements.txt
	@$(PIP) freeze --exclude-editable >> requirements.txt
	@echo "requirements.txt updated ($$(grep -c '==' requirements.txt) pinned packages)"

data:  ## Download and verify the raw dataset
	$(PY) -m churnsense.data.download

eda:  ## Regenerate reports/eda_report.md and reports/figures/*
	$(PY) -m churnsense.eda

train:  ## Train and compare all models; write artifacts/ and the comparison report
	$(PY) -m churnsense.models.train

evaluate:  ## Final (single) test-set evaluation + threshold economics
	$(PY) -m churnsense.evaluation.report

explain:  ## Compute and cache global SHAP values
	$(PY) -m churnsense.explainability.shap_explain

# `explain` runs before `evaluate`: the evaluation report embeds the cached
# SHAP importance figure, so the other order silently skips it on a first run.
all: data eda train explain evaluate  ## Full pipeline, raw data to reports

test:  ## Run the test suite
	$(PY) -m pytest

lint:  ## Lint with ruff
	$(PY) -m ruff check src app tests
	$(PY) -m ruff format --check src app tests

format:  ## Auto-format and auto-fix with ruff
	$(PY) -m ruff format src app tests
	$(PY) -m ruff check --fix src app tests

audit:  ## Check installed dependencies for known vulnerabilities
	@# --skip-editable: churnsense itself is installed editable and is not on
	@# PyPI, which --strict would report as an un-auditable dependency.
	$(PY) -m pip_audit --skip-editable

app:  ## Launch the Streamlit dashboard
	.venv/bin/streamlit run app/streamlit_app.py

api:  ## Launch the FastAPI service
	.venv/bin/uvicorn churnsense.api.main:app --host 127.0.0.1 --port 8000 --reload

clean:  ## Remove generated artifacts, reports and caches (raw data is kept)
	rm -rf artifacts/* reports/figures/* .pytest_cache .ruff_cache
	rm -f reports/*.md reports/*.json reports/*.csv
	find . -name __pycache__ -type d -prune -exec rm -rf {} +
	@mkdir -p artifacts reports/figures && touch artifacts/.gitkeep reports/figures/.gitkeep
	@echo "Cleaned. data/raw was left untouched."
