"""Shared test fixtures.

**Nothing here is real data.** Every row is generated by ``make_synthetic_raw``
from a seeded RNG, and every identifier is prefixed ``DEMO-`` so a synthetic
row can never be mistaken for an IBM Telco observation in a log, a screenshot
or a bug report. The test suite therefore runs in CI with no dataset download
and no network access.

The generator reproduces the dataset's *structure*, not its statistics: the
same columns, the same category vocabularies, the same "No internet service"
dependency between add-ons and ``InternetService``, and the same
blank-``TotalCharges``-at-zero-tenure quirk. A churn signal is injected through
contract type and tenure so that a model trained on the fixture learns
something and the end-to-end path is genuinely exercised - but the coefficients
it learns are meaningless and no test asserts a performance number.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd
import pytest

from churnsense.config import Config, load_config
from churnsense.data import schema

FIXTURE_DIR = Path(__file__).parent / "fixtures"
DEMO_CSV = FIXTURE_DIR / "demo_customers.csv"


def make_synthetic_raw(n: int = 400, seed: int = 0) -> pd.DataFrame:
    """Build a raw-shaped frame: all strings, same vocabularies as the real file."""
    rng = np.random.default_rng(seed)

    def pick(options: tuple[str, ...], p: list[float] | None = None) -> np.ndarray:
        return rng.choice(options, size=n, p=p)

    contract = pick(("Month-to-month", "One year", "Two year"), [0.55, 0.21, 0.24])
    tenure = np.where(
        contract == "Month-to-month",
        rng.integers(0, 40, n),
        rng.integers(12, 73, n),
    )
    # A handful of day-one customers, mirroring the real file's tenure == 0 rows.
    tenure[rng.choice(n, size=max(2, n // 100), replace=False)] = 0

    phone = pick(("Yes", "No"), [0.9, 0.1])
    internet = pick(("DSL", "Fiber optic", "No"), [0.34, 0.44, 0.22])
    has_internet = internet != "No"
    monthly = np.where(has_internet, rng.uniform(45, 119, n), rng.uniform(18, 40, n)).round(2)

    def addon() -> np.ndarray:
        """Add-ons are only purchasable with internet - mirror that dependency."""
        return np.where(has_internet, pick(("Yes", "No"), [0.4, 0.6]), "No internet service")

    # Churn probability driven by contract and tenure so the signal is learnable.
    base = np.where(
        contract == "Month-to-month", 0.45, np.where(contract == "One year", 0.14, 0.05)
    )
    churn_p = np.clip(base - tenure / 240, 0.02, 0.95)

    # Built as text up front rather than written over a float column afterwards:
    # reproduces the real file's blank-at-zero-tenure quirk without pandas having
    # to widen a float64 column to hold a space.
    total_charges = np.where(tenure == 0, " ", (tenure * monthly).round(2).astype(str))

    frame = pd.DataFrame(
        {
            schema.ID_COLUMN: [f"DEMO-{i:05d}" for i in range(n)],
            "gender": pick(("Female", "Male")),
            "SeniorCitizen": pick(("0", "1"), [0.84, 0.16]),
            "Partner": pick(("Yes", "No")),
            "Dependents": pick(("Yes", "No"), [0.3, 0.7]),
            "tenure": tenure,
            "PhoneService": phone,
            "MultipleLines": np.where(phone == "Yes", pick(("Yes", "No")), "No phone service"),
            "InternetService": internet,
            "OnlineSecurity": addon(),
            "OnlineBackup": addon(),
            "DeviceProtection": addon(),
            "TechSupport": addon(),
            "StreamingTV": addon(),
            "StreamingMovies": addon(),
            "Contract": contract,
            "PaperlessBilling": pick(("Yes", "No")),
            "PaymentMethod": pick(
                (
                    "Bank transfer (automatic)",
                    "Credit card (automatic)",
                    "Electronic check",
                    "Mailed check",
                )
            ),
            "MonthlyCharges": monthly,
            "TotalCharges": total_charges,
            schema.TARGET: np.where(rng.random(n) < churn_p, "Yes", "No"),
        }
    )

    return frame.astype(str)


@pytest.fixture(scope="session")
def raw_frame() -> pd.DataFrame:
    """Raw-shaped synthetic data, identical on every run."""
    return make_synthetic_raw()


@pytest.fixture(scope="session")
def demo_csv() -> Path:
    """Path to the committed demo CSV, regenerated if it drifts from the generator."""
    FIXTURE_DIR.mkdir(parents=True, exist_ok=True)
    expected = make_synthetic_raw(n=120, seed=7)
    if not DEMO_CSV.exists() or not pd.read_csv(DEMO_CSV, dtype=str).equals(expected):
        expected.to_csv(DEMO_CSV, index=False)
    return DEMO_CSV


@pytest.fixture(scope="session")
def clean_frame(raw_frame: pd.DataFrame) -> pd.DataFrame:
    from churnsense.data.loader import clean_frame as _clean

    return _clean(raw_frame)[0]


@pytest.fixture(scope="session")
def cfg() -> Config:
    return load_config()
